"""CLI entrypoint for openfusion."""

from __future__ import annotations

import argparse
import asyncio
import contextlib
import getpass
import os
import sys
from pathlib import Path

import uvicorn
import yaml
from pydantic import ValidationError

from openfusion.config import (
    _PRESETS,
    OPENROUTER_BASE_URL,
    Aggregator,
    OpenFusionConfig,
    Preset,
    load_config,
)
from openfusion.credentials import load_saved_key, save_key
from openfusion.overrides import (
    apply_overrides,
    fill_missing_keys,
    is_missing_api_key,
    set_all_keys,
)


def _summarize_config(config: OpenFusionConfig, host: str, port: int) -> str:
    """A short, human-readable summary of what's about to run."""
    judge = config.judge.model if config.judge else "—"
    panel = ", ".join(member.model for member in config.panel) or "—"
    recipe = (
        f"preset={config.preset.value}"
        if config.preset
        else f"strategy={config.strategy.value}"
    )
    tools = "web search+fetch" if config.tools.web_search else "off"
    lines = [
        "openfusion is starting",
        f"  recipe:   {recipe}  (aggregator={config.aggregator.value})",
        f"  panel:    {panel}",
        f"  judge:    {judge}",
        f"  tools:    {tools}",
        f"  listening on http://{host}:{port}",
        f'  call it with model="{config.fusion_model_name}" against http://{host}:{port}/v1',
    ]
    ui_host = "localhost" if host in ("0.0.0.0", "127.0.0.1") else host
    if is_missing_api_key(config):
        lines.append(
            f"  ⚠ no API key yet — open http://{ui_host}:{port} and paste your OpenRouter key, "
            "or run `openfusion setup`"
        )
    else:
        lines.append(f"  ▶ open the playground at http://{ui_host}:{port}")
    return "\n".join(lines)


def build_setup_yaml(preset: str, api_key: str) -> str:
    """Render an openfusion.yaml for the chosen preset with the key inlined."""
    spec = _PRESETS[Preset(preset)]
    config = {
        "aggregator": "judge",
        "tools": {"web_search": True, "web_fetch": True},
        "panel": [
            {"base_url": OPENROUTER_BASE_URL, "api_key": api_key, "model": model}
            for model in spec["panel_models"]
        ],
        "judge": {
            "base_url": OPENROUTER_BASE_URL,
            "api_key": api_key,
            "model": spec["judge_model"],
        },
        "pass_through": {
            "base_url": OPENROUTER_BASE_URL,
            "api_key": api_key,
            "model": spec["pass_through_model"],
        },
    }
    header = (
        "# Generated by `openfusion setup`. Keep this file private — it contains\n"
        "# your API key. It is gitignored by default.\n"
    )
    return header + yaml.safe_dump(config, sort_keys=False)


def run_setup() -> None:
    """Interactive first-run guide: write an openfusion.yaml and explain next steps."""
    print("openfusion setup — let's get you running.\n")
    path = Path("openfusion.yaml")
    if path.exists() and input(f"{path} already exists. Overwrite? [y/N] ").strip().lower() != "y":
        print("Keeping your existing config. Run `openfusion` to start.")
        return

    key = getpass.getpass("OpenRouter API key (get one at openrouter.ai/keys): ").strip()
    if not key:
        print(
            "\nNo key entered — that's fine. Start the server with `openfusion` and paste "
            "your key into the playground at http://localhost:8000."
        )
        return

    choice = input("Recipe — [1] Budget (cheaper)  [2] Quality (stronger)  [1/2, default 1]: ")
    preset = "quality" if choice.strip() == "2" else "budget"

    path.write_text(build_setup_yaml(preset, key), encoding="utf-8")
    with contextlib.suppress(OSError):
        path.chmod(0o600)
    save_key(key)  # also persist for `openfusion` runs from other directories

    print(
        f"\n✓ Wrote {path} ({preset} preset, panel + judge with web search).\n"
        "Next:\n"
        "  openfusion                 # start the server\n"
        "  open http://localhost:8000 # try it in the playground\n"
    )


async def _run_ask(prompt: str, config: OpenFusionConfig) -> None:
    from openfusion.panel import gather_panel
    from openfusion.ranked import pick_best
    from openfusion.synthesize import synthesize
    from openfusion.upstream import UpstreamClient
    from openfusion.vote import majority_vote

    client = UpstreamClient()
    body = {"messages": [{"role": "user", "content": prompt}]}
    try:
        print("· querying panel…", file=sys.stderr)
        panel = await gather_panel(body, config, client)
        print(
            f"· {len(panel.responses)} answered"
            + (f", {len(panel.failures)} failed" if panel.failures else ""),
            file=sys.stderr,
        )
        if config.aggregator == Aggregator.VOTE:
            content, _ = majority_vote(panel)
            print(content)
        elif config.aggregator == Aggregator.RANKED:
            content, _ = await pick_best(
                body, panel, config, client, timeout=config.timeouts.judge_seconds
            )
            print(content)
        else:
            print("· synthesizing…\n", file=sys.stderr)
            async for delta, _usage, _reason in synthesize(
                body, panel, config, client, timeout=config.timeouts.judge_seconds
            ):
                if delta:
                    sys.stdout.write(delta)
                    sys.stdout.flush()
            print()
    finally:
        await client.aclose()


def run_ask(prompt: str, config_path: str | None, max_tokens: int | None) -> None:
    try:
        config = load_config(config_path)
    except (FileNotFoundError, ValueError, ValidationError) as exc:
        print(f"openfusion: could not load configuration.\n{exc}", file=sys.stderr)
        raise SystemExit(1) from exc
    if max_tokens:
        config = apply_overrides(config, {"max_tokens": max_tokens})
    config = fill_missing_keys(config, load_saved_key())
    if is_missing_api_key(config):
        print(
            "openfusion: no upstream API key. Set OPENROUTER_API_KEY or run `openfusion setup`.",
            file=sys.stderr,
        )
        raise SystemExit(1)
    asyncio.run(_run_ask(prompt, config))


def _ask_cli(argv: list[str]) -> None:
    parser = argparse.ArgumentParser(
        prog="openfusion ask", description="Run one fusion prompt and print the answer"
    )
    parser.add_argument("prompt", help="The prompt to fuse")
    parser.add_argument("--config", default=os.environ.get("OPENFUSION_CONFIG"))
    parser.add_argument("--max-tokens", type=int, default=None, help="Cap tokens per call")
    args = parser.parse_args(argv)
    run_ask(args.prompt, args.config, args.max_tokens)


async def _chat_turn(
    messages: list[dict[str, str]], config: OpenFusionConfig, console: object | None = None
) -> str:
    """Run one fusion turn over the conversation; return the answer text.

    With a Rich ``console`` it renders a spinner + live Markdown; without one
    (pipes/tests) it streams plain text to stdout.
    """
    from openfusion.panel import expand_panel_members, gather_panel
    from openfusion.ranked import pick_best
    from openfusion.synthesize import synthesize
    from openfusion.upstream import UpstreamClient
    from openfusion.vote import majority_vote

    client = UpstreamClient()
    body = {"messages": messages}
    parts: list[str] = []
    try:
        if console is None:
            sys.stderr.write("\033[2m· querying panel…\033[0m\n")
            sys.stderr.flush()
            panel = await gather_panel(body, config, client)
            if config.aggregator in (Aggregator.VOTE, Aggregator.RANKED):
                if config.aggregator == Aggregator.VOTE:
                    content, _ = majority_vote(panel)
                else:
                    content, _ = await pick_best(
                        body, panel, config, client, timeout=config.timeouts.judge_seconds
                    )
                print(content)
                parts.append(content)
            else:
                async for delta, _u, _r in synthesize(
                    body, panel, config, client, timeout=config.timeouts.judge_seconds
                ):
                    if delta:
                        sys.stdout.write(delta)
                        sys.stdout.flush()
                        parts.append(delta)
                print()
            return "".join(parts)

        from rich.live import Live
        from rich.markdown import Markdown

        total = len(expand_panel_members(config))
        done = {"n": 0}
        content: str | None = None
        with console.status("[dim]querying panel…[/dim]", spinner="dots") as status:

            async def on_member(_label: str, _model: str, _ok: bool, _content: str) -> None:
                done["n"] += 1
                status.update(f"[dim]querying panel · {done['n']}/{total} answered[/dim]")

            panel = await gather_panel(body, config, client, on_member=on_member)
            status.update("[dim]synthesizing…[/dim]")
            if config.aggregator == Aggregator.VOTE:
                content, _ = majority_vote(panel)
            elif config.aggregator == Aggregator.RANKED:
                content, _ = await pick_best(
                    body, panel, config, client, timeout=config.timeouts.judge_seconds
                )

        console.print("[bold magenta]●[/bold magenta] [bold]openfusion[/bold]")
        if content is not None:
            parts.append(content)
            console.print(Markdown(content))
        else:
            with Live(console=console, refresh_per_second=12, vertical_overflow="visible") as live:
                async for delta, _u, _r in synthesize(
                    body, panel, config, client, timeout=config.timeouts.judge_seconds
                ):
                    if delta:
                        parts.append(delta)
                        live.update(Markdown("".join(parts)))
        console.print()
    finally:
        await client.aclose()
    return "".join(parts)


def _models_markup(config: OpenFusionConfig) -> str:
    panel = ", ".join(m.model for m in config.panel) or "—"
    judge = config.judge.model if config.judge else "—"
    return (
        f"[dim]panel:[/dim] {panel}\n"
        f"[dim]judge:[/dim] {judge}  [dim]·[/dim] {config.aggregator.value}"
    )


_CHAT_HELP = """\
[bold]Commands[/bold]
  [cyan]/help[/cyan]            show this help
  [cyan]/models[/cyan]          show the active panel and judge
  [cyan]/preset[/cyan] NAME     switch recipe (quality | budget)
  [cyan]/tokens[/cyan] N        cap tokens per call
  [cyan]/key[/cyan]             re-enter your OpenRouter API key
  [cyan]/clear[/cyan]           reset the conversation
  [cyan]/quit[/cyan]            exit  (or Ctrl-D)"""


def run_chat(config_path: str | None, max_tokens: int | None) -> None:
    """Interactive REPL: chat with the model panel right in the terminal."""
    from rich.console import Console
    from rich.panel import Panel

    console = Console()
    with contextlib.suppress(ImportError):
        import readline  # noqa: F401 - arrow-key history for input()

    try:
        config = load_config(config_path)
    except (FileNotFoundError, ValueError, ValidationError) as exc:
        console.print(f"[red]openfusion:[/red] could not load configuration.\n{exc}")
        raise SystemExit(1) from exc
    if max_tokens:
        config = apply_overrides(config, {"max_tokens": max_tokens})

    if is_missing_api_key(config):
        config = fill_missing_keys(config, load_saved_key())
    if is_missing_api_key(config) and sys.stdin.isatty():
        key = getpass.getpass("OpenRouter API key (saved for next time): ").strip()
        if key:
            config = fill_missing_keys(config, key)
            save_key(key)
            console.print("[dim]· key saved to ~/.config/openfusion/credentials[/dim]")
    if is_missing_api_key(config):
        console.print(
            "[red]openfusion:[/red] no upstream API key. "
            "Set OPENROUTER_API_KEY or run `openfusion setup`."
        )
        raise SystemExit(1)

    base_config = config
    console.print(
        Panel(
            f"[bold]openfusion[/bold] — chat with a model panel\n{_models_markup(config)}\n"
            "[dim]/help for commands · Ctrl-D to exit[/dim]",
            border_style="magenta",
            expand=False,
        )
    )
    messages: list[dict[str, str]] = []

    while True:
        try:
            line = console.input("\n[bold cyan]›[/bold cyan] ").strip()
        except (EOFError, KeyboardInterrupt):
            console.print("\n[dim]bye[/dim]")
            return
        if not line:
            continue
        if line.startswith("/"):
            tokens = line[1:].split(maxsplit=1)
            cmd = tokens[0].lower()
            arg = tokens[1].strip() if len(tokens) > 1 else ""
            if cmd in ("q", "quit", "exit"):
                console.print("[dim]bye[/dim]")
                return
            elif cmd in ("h", "help", "?"):
                console.print(_CHAT_HELP)
            elif cmd == "models":
                console.print(_models_markup(config))
            elif cmd == "clear":
                messages.clear()
                console.print("[dim]· conversation cleared[/dim]")
            elif cmd == "preset":
                if arg in ("quality", "budget"):
                    config = apply_overrides(base_config, {"preset": arg})
                    console.print(f"[dim]· switched to {arg}[/dim]")
                    console.print(_models_markup(config))
                else:
                    console.print("usage: /preset quality|budget")
            elif cmd == "tokens":
                if arg.isdigit() and int(arg) > 0:
                    config = apply_overrides(config, {"max_tokens": int(arg)})
                    console.print(f"[dim]· max tokens per call = {arg}[/dim]")
                else:
                    console.print("usage: /tokens <n>")
            elif cmd == "key":
                new_key = getpass.getpass("OpenRouter API key: ").strip()
                if new_key:
                    config = set_all_keys(config, new_key)
                    base_config = set_all_keys(base_config, new_key)
                    save_key(new_key)
                    console.print("[dim]· key updated and saved[/dim]")
            else:
                console.print(f"unknown command: /{cmd} (try /help)")
            continue

        messages.append({"role": "user", "content": line})
        try:
            answer = asyncio.run(_chat_turn(messages, config, console))
        except KeyboardInterrupt:
            console.print("[dim]· cancelled[/dim]")
            messages.pop()
            continue
        except Exception as exc:  # noqa: BLE001 - keep the REPL alive on errors
            msg = str(exc)
            console.print(f"[red][error][/red] {msg}")
            low = msg.lower()
            if "401" in msg or "api key" in low or "unauthor" in low or "credit" in low:
                console.print(
                    "[dim]· the key may be invalid or out of credit — use /key to re-enter it[/dim]"
                )
            messages.pop()
            continue
        messages.append({"role": "assistant", "content": answer})


def run_server(argv: list[str]) -> None:
    parser = argparse.ArgumentParser(
        prog="openfusion web", description="Start the openfusion server + web playground"
    )
    parser.add_argument("--host", default=os.environ.get("OPENFUSION_HOST", "0.0.0.0"))
    parser.add_argument("--port", type=int, default=int(os.environ.get("OPENFUSION_PORT", "8000")))
    parser.add_argument("--config", default=os.environ.get("OPENFUSION_CONFIG"))
    parser.add_argument("--reload", action="store_true")
    parser.add_argument(
        "--no-open", action="store_true", help="Don't open the playground in a browser"
    )
    args = parser.parse_args(argv)

    # Ensure the uvicorn factory (which re-loads config in the worker) honors
    # an explicit --config, not just the OPENFUSION_CONFIG env var.
    if args.config:
        os.environ["OPENFUSION_CONFIG"] = args.config

    try:
        config = load_config(args.config)
    except (FileNotFoundError, ValueError, ValidationError) as exc:
        print(f"openfusion: could not load configuration.\n{exc}", file=sys.stderr)
        raise SystemExit(1) from exc

    print(_summarize_config(config, args.host, args.port), file=sys.stderr)
    os.environ["OPENFUSION_LOADED_CONFIG"] = "1"

    # Pop the playground open once the server is up — but only for an interactive
    # local terminal (skip Docker/CI/headless and `--no-open`/OPENFUSION_NO_OPEN).
    if (
        not args.no_open
        and not os.environ.get("OPENFUSION_NO_OPEN")
        and sys.stdout.isatty()
        and not args.reload
    ):
        ui_host = "localhost" if args.host in ("0.0.0.0", "127.0.0.1", "") else args.host
        url = f"http://{ui_host}:{args.port}/playground/"

        def _open() -> None:
            import time
            import webbrowser

            time.sleep(1.2)
            with contextlib.suppress(Exception):
                webbrowser.open(url)

        import threading

        threading.Thread(target=_open, daemon=True).start()

    uvicorn.run(
        "openfusion.server:create_app",
        factory=True,
        host=args.host,
        port=args.port,
        reload=args.reload,
        log_level=os.environ.get("OPENFUSION_LOG_LEVEL", "info"),
    )


_HELP = """\
openfusion — open mixture-of-agents

Usage:
  openfusion                  Chat with the model panel (interactive)
  openfusion ask "PROMPT"     Run one fusion and print the answer
  openfusion web              Start the server + web playground
  openfusion setup            Guided first-run setup
  echo "PROMPT" | openfusion  Pipe a one-shot prompt

Run `openfusion web --help` for server options."""


def main() -> None:
    argv = sys.argv[1:]
    if argv and argv[0] in ("-h", "--help"):
        print(_HELP)
        return

    cmd = argv[0] if argv and not argv[0].startswith("-") else None
    if cmd in ("web", "serve"):
        run_server(argv[1:])
        return
    if cmd == "ask":
        _ask_cli(argv[1:])
        return
    if cmd == "setup":
        run_setup()
        return
    if cmd == "chat":
        run_chat(os.environ.get("OPENFUSION_CONFIG"), None)
        return
    if cmd is not None:
        print(f"openfusion: unknown command '{cmd}'\n", file=sys.stderr)
        print(_HELP, file=sys.stderr)
        raise SystemExit(2)

    # Bare `openfusion`: interactive chat in a TTY; pipe support otherwise.
    if not sys.stdin.isatty():
        piped = sys.stdin.read().strip()
        if piped:
            run_ask(piped, os.environ.get("OPENFUSION_CONFIG"), None)
        else:
            print(_HELP)
        return
    run_chat(os.environ.get("OPENFUSION_CONFIG"), None)


if __name__ == "__main__":
    main()
