"""CLI entrypoint for openfusion."""

from __future__ import annotations

import argparse
import contextlib
import getpass
import os
import sys
from pathlib import Path

import uvicorn
import yaml
from pydantic import ValidationError

from openfusion.config import (
    _PRESETS,
    OPENROUTER_BASE_URL,
    OpenFusionConfig,
    Preset,
    load_config,
)
from openfusion.overrides import is_missing_api_key


def _summarize_config(config: OpenFusionConfig, host: str, port: int) -> str:
    """A short, human-readable summary of what's about to run."""
    judge = config.judge.model if config.judge else "—"
    panel = ", ".join(member.model for member in config.panel) or "—"
    recipe = (
        f"preset={config.preset.value}"
        if config.preset
        else f"strategy={config.strategy.value}"
    )
    tools = "web search+fetch" if config.tools.web_search else "off"
    lines = [
        "openfusion is starting",
        f"  recipe:   {recipe}  (aggregator={config.aggregator.value})",
        f"  panel:    {panel}",
        f"  judge:    {judge}",
        f"  tools:    {tools}",
        f"  listening on http://{host}:{port}",
        f'  call it with model="{config.fusion_model_name}" against http://{host}:{port}/v1',
    ]
    ui_host = "localhost" if host in ("0.0.0.0", "127.0.0.1") else host
    if is_missing_api_key(config):
        lines.append(
            f"  ⚠ no API key yet — open http://{ui_host}:{port} and paste your OpenRouter key, "
            "or run `openfusion setup`"
        )
    else:
        lines.append(f"  ▶ open the playground at http://{ui_host}:{port}")
    return "\n".join(lines)


def build_setup_yaml(preset: str, api_key: str) -> str:
    """Render an openfusion.yaml for the chosen preset with the key inlined."""
    spec = _PRESETS[Preset(preset)]
    config = {
        "aggregator": "judge",
        "tools": {"web_search": True, "web_fetch": True},
        "panel": [
            {"base_url": OPENROUTER_BASE_URL, "api_key": api_key, "model": model}
            for model in spec["panel_models"]
        ],
        "judge": {
            "base_url": OPENROUTER_BASE_URL,
            "api_key": api_key,
            "model": spec["judge_model"],
        },
        "pass_through": {
            "base_url": OPENROUTER_BASE_URL,
            "api_key": api_key,
            "model": spec["pass_through_model"],
        },
    }
    header = (
        "# Generated by `openfusion setup`. Keep this file private — it contains\n"
        "# your API key. It is gitignored by default.\n"
    )
    return header + yaml.safe_dump(config, sort_keys=False)


def run_setup() -> None:
    """Interactive first-run guide: write an openfusion.yaml and explain next steps."""
    print("openfusion setup — let's get you running.\n")
    path = Path("openfusion.yaml")
    if path.exists() and input(f"{path} already exists. Overwrite? [y/N] ").strip().lower() != "y":
        print("Keeping your existing config. Run `openfusion` to start.")
        return

    key = getpass.getpass("OpenRouter API key (get one at openrouter.ai/keys): ").strip()
    if not key:
        print(
            "\nNo key entered — that's fine. Start the server with `openfusion` and paste "
            "your key into the playground at http://localhost:8000."
        )
        return

    choice = input("Recipe — [1] Budget (cheaper)  [2] Quality (stronger)  [1/2, default 1]: ")
    preset = "quality" if choice.strip() == "2" else "budget"

    path.write_text(build_setup_yaml(preset, key), encoding="utf-8")
    with contextlib.suppress(OSError):
        path.chmod(0o600)

    print(
        f"\n✓ Wrote {path} ({preset} preset, panel + judge with web search).\n"
        "Next:\n"
        "  openfusion                 # start the server\n"
        "  open http://localhost:8000 # try it in the playground\n"
    )


def main() -> None:
    if len(sys.argv) > 1 and sys.argv[1] == "setup":
        run_setup()
        return

    parser = argparse.ArgumentParser(description="Run the openfusion proxy server")
    parser.add_argument("--host", default=os.environ.get("OPENFUSION_HOST", "0.0.0.0"))
    parser.add_argument("--port", type=int, default=int(os.environ.get("OPENFUSION_PORT", "8000")))
    parser.add_argument("--config", default=os.environ.get("OPENFUSION_CONFIG"))
    parser.add_argument("--reload", action="store_true")
    args = parser.parse_args()

    # Ensure the uvicorn factory (which re-loads config in the worker) honors
    # an explicit --config, not just the OPENFUSION_CONFIG env var.
    if args.config:
        os.environ["OPENFUSION_CONFIG"] = args.config

    try:
        config = load_config(args.config)
    except (FileNotFoundError, ValueError, ValidationError) as exc:
        print(f"openfusion: could not load configuration.\n{exc}", file=sys.stderr)
        raise SystemExit(1) from exc

    print(_summarize_config(config, args.host, args.port), file=sys.stderr)
    os.environ["OPENFUSION_LOADED_CONFIG"] = "1"

    uvicorn.run(
        "openfusion.server:create_app",
        factory=True,
        host=args.host,
        port=args.port,
        reload=args.reload,
        log_level=os.environ.get("OPENFUSION_LOG_LEVEL", "info"),
    )


if __name__ == "__main__":
    main()
